# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc5dc6cb2ade5b9a2b8b033b5f5739e0ba2e71933bc03f6f9d8e494b597d1e8d45d0cab15300d9fb8c689106e56a7cc7008b4af4a9f945db8dc5092a9149f0b0

test:
  secret_key_base: 03737b9fb1314829cbea502e4091da5575b8b917987b02d21291cf40f03f541ca2be1c62a6c66d51bdb839d350656258bd4aa812ac916343c0d5b64dc0e7efeb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
